/**
 * @build-unit BU-network-feed
 * @spec architecture/decision-log.md (D083)
 * @spec adrs/0017-network-card-state.md
 *
 * Zod validation schemas for the network tRPC router. Mirrors the
 * Prisma enum `NetworkCardStatus` and the upstream `messageId`
 * BigInt key (Grant's `gps_group_messages.id`).
 *
 * superjson is the tRPC transformer (server/lib/trpc.ts), so
 * z.bigint() at the boundary is honoured — clients pass real
 * bigints and zod validates them as such.
 */

import { z } from 'zod';

/** Mirrors Prisma's NetworkCardStatus enum. Keep in sync. */
export const NetworkCardStatusSchema = z.enum(['NEW', 'TRIAGED', 'PROMOTED', 'DISCARDED']);

export type NetworkCardStatusValue = z.infer<typeof NetworkCardStatusSchema>;

/** Upper bound on the rolling window (days). 90 was locked in the brief. */
export const NETWORK_LIST_MAX_WINDOW_DAYS = 90;

/** Upper bound on a single page. 50 keeps the wire payload tight at v1 volume. */
export const NETWORK_LIST_MAX_LIMIT = 50;

/**
 * bu-network-source-chips — source slug shape. Kebab-case (auto-
 * generated by Grant's INSERT trigger from the label). Bounded at
 * 64 chars to match what the trigger can produce from a sane label
 * length and to keep the URL state tractable.
 */
export const SOURCE_SLUG_REGEX = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export const SOURCE_SLUG_MAX_LENGTH = 64;
export const networkSourceSlugSchema = z
  .string()
  .min(1)
  .max(SOURCE_SLUG_MAX_LENGTH)
  .regex(SOURCE_SLUG_REGEX, 'Source slug must be kebab-case (lowercase letters, digits, hyphens).');

export const networkListSchema = z.object({
  limit: z.number().int().positive().max(NETWORK_LIST_MAX_LIMIT).default(NETWORK_LIST_MAX_LIMIT),
  /** Opaque cursor — encodes the last-seen `id` for pagination. */
  cursor: z.string().optional(),
  /** Days to look back. Defaults to the brief-locked 90-day window. */
  windowDays: z
    .number()
    .int()
    .positive()
    .max(NETWORK_LIST_MAX_WINDOW_DAYS)
    .default(NETWORK_LIST_MAX_WINDOW_DAYS),
  /** Bypass the cache and fetch fresh. Used by the manual-refresh affordance. */
  refresh: z.boolean().default(false),
  /**
   * bu-network-source-chips — filter cards to one or more sources by
   * `slug`. Empty array = no filter (equivalent to absent — "All").
   * Each slug validated as kebab-case; unknown slugs are silently
   * ignored at the service layer (no error — keeps shared URLs from
   * 400-ing when a chip is later retired).
   */
  sources: z.array(networkSourceSlugSchema).default([]),
});

export type NetworkListInput = z.infer<typeof networkListSchema>;

/**
 * bu-network-source-chips — listSources procedure has no inputs; the
 * schema is here for symmetry and to keep the router signature
 * consistent with the rest of the surface.
 */
export const networkListSourcesSchema = z.object({}).default({});

export type NetworkListSourcesInput = z.infer<typeof networkListSourcesSchema>;

export const networkSetCardStateSchema = z.object({
  /** Grant's `gps_group_messages.id` — opaque BigInt join key (ADR-0017). */
  messageId: z.bigint(),
  status: NetworkCardStatusSchema,
  /** Optional explicit owner. Null clears ownership. */
  ownerUserId: z.string().uuid().nullable().optional(),
  /** Optional triage note (max 500 chars to keep the surface light). */
  notes: z.string().max(500).nullable().optional(),
});

export type NetworkSetCardStateInput = z.infer<typeof networkSetCardStateSchema>;
