/**
 * @build-unit BU-network-feed
 * @spec architecture/decision-log.md (D083)
 * @spec adrs/0017-network-card-state.md
 *
 * Zod validation schemas for the network tRPC router. Mirrors the
 * Prisma enum `NetworkCardStatus` and the upstream `messageId`
 * BigInt key (Grant's `gps_group_messages.id`).
 *
 * superjson is the tRPC transformer (server/lib/trpc.ts), so
 * z.bigint() at the boundary is honoured — clients pass real
 * bigints and zod validates them as such.
 */

import { z } from 'zod';

/** Mirrors Prisma's NetworkCardStatus enum. Keep in sync. */
export const NetworkCardStatusSchema = z.enum(['NEW', 'TRIAGED', 'PROMOTED', 'DISCARDED']);

export type NetworkCardStatusValue = z.infer<typeof NetworkCardStatusSchema>;

/** Upper bound on the rolling window (days). 90 was locked in the brief. */
export const NETWORK_LIST_MAX_WINDOW_DAYS = 90;

/** Upper bound on a single page. 50 keeps the wire payload tight at v1 volume. */
export const NETWORK_LIST_MAX_LIMIT = 50;

/**
 * bu-network-source-chips — source slug shape. Kebab-case (auto-
 * generated by Grant's INSERT trigger from the label). Bounded at
 * 64 chars to match what the trigger can produce from a sane label
 * length and to keep the URL state tractable.
 */
export const SOURCE_SLUG_REGEX = /^[a-z0-9]+(?:-[a-z0-9]+)*$/;
export const SOURCE_SLUG_MAX_LENGTH = 64;
export const networkSourceSlugSchema = z
  .string()
  .min(1)
  .max(SOURCE_SLUG_MAX_LENGTH)
  .regex(SOURCE_SLUG_REGEX, 'Source slug must be kebab-case (lowercase letters, digits, hyphens).');

/**
 * bu-network-sort-options — v1 axes. Both axes use the same compound
 * (sent_at, id) sort key — `recent` is DESC, `oldest` is ASC. Other
 * candidates from the brief (most-reacted, most-shared, triage-status)
 * need backend joins and stay parked until shipped separately.
 */
export const NETWORK_SORT_OPTIONS = ['recent', 'oldest'] as const;
export const networkSortSchema = z.enum(NETWORK_SORT_OPTIONS);
export type NetworkSort = z.infer<typeof networkSortSchema>;

export const networkListSchema = z.object({
  limit: z.number().int().positive().max(NETWORK_LIST_MAX_LIMIT).default(NETWORK_LIST_MAX_LIMIT),
  /** Opaque cursor — encodes the last-seen `id` for pagination. */
  cursor: z.string().optional(),
  /** Days to look back. Defaults to the brief-locked 90-day window. */
  windowDays: z
    .number()
    .int()
    .positive()
    .max(NETWORK_LIST_MAX_WINDOW_DAYS)
    .default(NETWORK_LIST_MAX_WINDOW_DAYS),
  /** Bypass the cache and fetch fresh. Used by the manual-refresh affordance. */
  refresh: z.boolean().default(false),
  /**
   * bu-network-source-chips — filter cards to one or more sources by
   * `slug`. Empty array = no filter (equivalent to absent — "All").
   * Each slug validated as kebab-case; unknown slugs are silently
   * ignored at the service layer (no error — keeps shared URLs from
   * 400-ing when a chip is later retired).
   */
  sources: z.array(networkSourceSlugSchema).default([]),
  /**
   * bu-network-sort-options — member-facing sort direction.
   * `recent` (default) = newest sent_at first; `oldest` = ascending.
   * Both use the same compound (sent_at, id) sort key so pagination
   * is keyset-stable on either axis.
   */
  sort: networkSortSchema.default('recent'),
});

export type NetworkListInput = z.infer<typeof networkListSchema>;

/**
 * bu-network-source-chips — listSources procedure has no inputs; the
 * schema is here for symmetry and to keep the router signature
 * consistent with the rest of the surface.
 */
export const networkListSourcesSchema = z.object({}).default({});

export type NetworkListSourcesInput = z.infer<typeof networkListSourcesSchema>;

export const networkSetCardStateSchema = z.object({
  /** Grant's `gps_group_messages.id` — opaque BigInt join key (ADR-0017). */
  messageId: z.bigint(),
  status: NetworkCardStatusSchema,
  /** Optional explicit owner. Null clears ownership. */
  ownerUserId: z.string().uuid().nullable().optional(),
  /** Optional triage note (max 500 chars to keep the surface light). */
  notes: z.string().max(500).nullable().optional(),
});

export type NetworkSetCardStateInput = z.infer<typeof networkSetCardStateSchema>;

/**
 * bu-network-spread-gallery — input schema for `network.spread.list`.
 *
 * Sources is the same kebab-case slug list as the feed; types is the
 * five buckets from `bu-link-preview-store`. Both default to empty
 * (no filter / "All"). Sort defaults to `mostSpread` per the
 * brief-locked decision.
 */
export const SPREAD_SORT_OPTIONS = ['mostSpread', 'trending', 'mostRecent'] as const;
export const spreadSortSchema = z.enum(SPREAD_SORT_OPTIONS);
export type SpreadSort = z.infer<typeof spreadSortSchema>;

export const SPREAD_LINK_TYPES = ['Social', 'Video', 'News', 'Action', 'Other'] as const;
export const spreadLinkTypeSchema = z.enum(SPREAD_LINK_TYPES);
export type SpreadLinkType = z.infer<typeof spreadLinkTypeSchema>;

export const NETWORK_SPREAD_DEFAULT_WINDOW_DAYS = 30;
export const NETWORK_SPREAD_MAX_WINDOW_DAYS = 90;

export const networkSpreadListSchema = z.object({
  windowDays: z
    .number()
    .int()
    .positive()
    .max(NETWORK_SPREAD_MAX_WINDOW_DAYS)
    .default(NETWORK_SPREAD_DEFAULT_WINDOW_DAYS),
  sources: z.array(networkSourceSlugSchema).default([]),
  types: z.array(spreadLinkTypeSchema).default([]),
  sort: spreadSortSchema.default('mostSpread'),
});

export type NetworkSpreadListInput = z.infer<typeof networkSpreadListSchema>;
